services:
  mysql: #<-서비스 이름
    image: mysql:8.4 
    container_name: mysql-dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: game_db
      MYSQL_USER: game_user
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: